// Autogenerated from Pigeon (v24.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum TransportTypeMessage: Int {
  case all = 0
  case webSockets = 1
  case longPolling = 2
}

enum HubConnectionStateMessage: Int {
  case connected = 0
  case connecting = 1
  case disconnected = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct HandledHubMethodMessage {
  var methodName: String
  var argCount: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HandledHubMethodMessage? {
    let methodName = pigeonVar_list[0] as! String
    let argCount = pigeonVar_list[1] as! Int64

    return HandledHubMethodMessage(
      methodName: methodName,
      argCount: argCount
    )
  }
  func toList() -> [Any?] {
    return [
      methodName,
      argCount,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CreateHubConnectionManagerMessage {
  var baseUrl: String
  var transportType: TransportTypeMessage
  var headers: [String?: String?]? = nil
  var accessToken: String? = nil
  var handShakeResponseTimeoutInMilliseconds: Int64
  var keepAliveIntervalInMilliseconds: Int64
  var serverTimeoutInMilliseconds: Int64
  var handledHubMethods: [HandledHubMethodMessage?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CreateHubConnectionManagerMessage? {
    let baseUrl = pigeonVar_list[0] as! String
    let transportType = pigeonVar_list[1] as! TransportTypeMessage
    let headers: [String?: String?]? = nilOrValue(pigeonVar_list[2])
    let accessToken: String? = nilOrValue(pigeonVar_list[3])
    let handShakeResponseTimeoutInMilliseconds = pigeonVar_list[4] as! Int64
    let keepAliveIntervalInMilliseconds = pigeonVar_list[5] as! Int64
    let serverTimeoutInMilliseconds = pigeonVar_list[6] as! Int64
    let handledHubMethods: [HandledHubMethodMessage?]? = nilOrValue(pigeonVar_list[7])

    return CreateHubConnectionManagerMessage(
      baseUrl: baseUrl,
      transportType: transportType,
      headers: headers,
      accessToken: accessToken,
      handShakeResponseTimeoutInMilliseconds: handShakeResponseTimeoutInMilliseconds,
      keepAliveIntervalInMilliseconds: keepAliveIntervalInMilliseconds,
      serverTimeoutInMilliseconds: serverTimeoutInMilliseconds,
      handledHubMethods: handledHubMethods
    )
  }
  func toList() -> [Any?] {
    return [
      baseUrl,
      transportType,
      headers,
      accessToken,
      handShakeResponseTimeoutInMilliseconds,
      keepAliveIntervalInMilliseconds,
      serverTimeoutInMilliseconds,
      handledHubMethods,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HubConnectionManagerIdMessage {
  var hubConnectionManagerId: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HubConnectionManagerIdMessage? {
    let hubConnectionManagerId = pigeonVar_list[0] as! Int64

    return HubConnectionManagerIdMessage(
      hubConnectionManagerId: hubConnectionManagerId
    )
  }
  func toList() -> [Any?] {
    return [
      hubConnectionManagerId
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct InvokeHubMethodMessage {
  var methodName: String
  var args: [String?]? = nil
  var hubConnectionManagerIdMessage: HubConnectionManagerIdMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> InvokeHubMethodMessage? {
    let methodName = pigeonVar_list[0] as! String
    let args: [String?]? = nilOrValue(pigeonVar_list[1])
    let hubConnectionManagerIdMessage = pigeonVar_list[2] as! HubConnectionManagerIdMessage

    return InvokeHubMethodMessage(
      methodName: methodName,
      args: args,
      hubConnectionManagerIdMessage: hubConnectionManagerIdMessage
    )
  }
  func toList() -> [Any?] {
    return [
      methodName,
      args,
      hubConnectionManagerIdMessage,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OnHubConnectionStateChangedMessage {
  var state: HubConnectionStateMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OnHubConnectionStateChangedMessage? {
    let state = pigeonVar_list[0] as! HubConnectionStateMessage

    return OnHubConnectionStateChangedMessage(
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      state
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OnHubConnectionClosedMessage {
  var exceptionMessage: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OnHubConnectionClosedMessage? {
    let exceptionMessage = pigeonVar_list[0] as! String

    return OnHubConnectionClosedMessage(
      exceptionMessage: exceptionMessage
    )
  }
  func toList() -> [Any?] {
    return [
      exceptionMessage
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OnMessageReceivedMessage {
  var methodName: String
  var args: [String?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OnMessageReceivedMessage? {
    let methodName = pigeonVar_list[0] as! String
    let args: [String?]? = nilOrValue(pigeonVar_list[1])

    return OnMessageReceivedMessage(
      methodName: methodName,
      args: args
    )
  }
  func toList() -> [Any?] {
    return [
      methodName,
      args,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SetBaseUrlMessage {
  var baseUrl: String
  var hubConnectionManagerIdMessage: HubConnectionManagerIdMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SetBaseUrlMessage? {
    let baseUrl = pigeonVar_list[0] as! String
    let hubConnectionManagerIdMessage = pigeonVar_list[1] as! HubConnectionManagerIdMessage

    return SetBaseUrlMessage(
      baseUrl: baseUrl,
      hubConnectionManagerIdMessage: hubConnectionManagerIdMessage
    )
  }
  func toList() -> [Any?] {
    return [
      baseUrl,
      hubConnectionManagerIdMessage,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return TransportTypeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return HubConnectionStateMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return HandledHubMethodMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return CreateHubConnectionManagerMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return HubConnectionManagerIdMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return InvokeHubMethodMessage.fromList(self.readValue() as! [Any?])
    case 135:
      return OnHubConnectionStateChangedMessage.fromList(self.readValue() as! [Any?])
    case 136:
      return OnHubConnectionClosedMessage.fromList(self.readValue() as! [Any?])
    case 137:
      return OnMessageReceivedMessage.fromList(self.readValue() as! [Any?])
    case 138:
      return SetBaseUrlMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? TransportTypeMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? HubConnectionStateMessage {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? HandledHubMethodMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? CreateHubConnectionManagerMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? HubConnectionManagerIdMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? InvokeHubMethodMessage {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? OnHubConnectionStateChangedMessage {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? OnHubConnectionClosedMessage {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? OnMessageReceivedMessage {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? SetBaseUrlMessage {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Used to communicate with hub connections managers on the native side.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HubConnectionManagerNativeApi {
  func createHubConnectionManager(msg: CreateHubConnectionManagerMessage, completion: @escaping (Result<HubConnectionManagerIdMessage, Error>) -> Void)
  func startHubConnection(msg: HubConnectionManagerIdMessage, completion: @escaping (Result<String, Error>) -> Void)
  func stopHubConnection(msg: HubConnectionManagerIdMessage, completion: @escaping (Result<Void, Error>) -> Void)
  func getConnectionId(msg: HubConnectionManagerIdMessage, completion: @escaping (Result<String?, Error>) -> Void)
  func getConnectionState(msg: HubConnectionManagerIdMessage, completion: @escaping (Result<HubConnectionStateMessage, Error>) -> Void)
  func invoke(msg: InvokeHubMethodMessage, completion: @escaping (Result<Void, Error>) -> Void)
  func setBaseUrl(msg: SetBaseUrlMessage, completion: @escaping (Result<Void, Error>) -> Void)
  func disposeHubConnectionManager(msg: HubConnectionManagerIdMessage, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HubConnectionManagerNativeApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `HubConnectionManagerNativeApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HubConnectionManagerNativeApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let createHubConnectionManagerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fsignalr.HubConnectionManagerNativeApi.createHubConnectionManager\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createHubConnectionManagerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let msgArg = args[0] as! CreateHubConnectionManagerMessage
        api.createHubConnectionManager(msg: msgArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createHubConnectionManagerChannel.setMessageHandler(nil)
    }
    let startHubConnectionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fsignalr.HubConnectionManagerNativeApi.startHubConnection\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startHubConnectionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let msgArg = args[0] as! HubConnectionManagerIdMessage
        api.startHubConnection(msg: msgArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startHubConnectionChannel.setMessageHandler(nil)
    }
    let stopHubConnectionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fsignalr.HubConnectionManagerNativeApi.stopHubConnection\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopHubConnectionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let msgArg = args[0] as! HubConnectionManagerIdMessage
        api.stopHubConnection(msg: msgArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopHubConnectionChannel.setMessageHandler(nil)
    }
    let getConnectionIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fsignalr.HubConnectionManagerNativeApi.getConnectionId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getConnectionIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let msgArg = args[0] as! HubConnectionManagerIdMessage
        api.getConnectionId(msg: msgArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getConnectionIdChannel.setMessageHandler(nil)
    }
    let getConnectionStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fsignalr.HubConnectionManagerNativeApi.getConnectionState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getConnectionStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let msgArg = args[0] as! HubConnectionManagerIdMessage
        api.getConnectionState(msg: msgArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getConnectionStateChannel.setMessageHandler(nil)
    }
    let invokeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fsignalr.HubConnectionManagerNativeApi.invoke\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      invokeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let msgArg = args[0] as! InvokeHubMethodMessage
        api.invoke(msg: msgArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      invokeChannel.setMessageHandler(nil)
    }
    let setBaseUrlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fsignalr.HubConnectionManagerNativeApi.setBaseUrl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setBaseUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let msgArg = args[0] as! SetBaseUrlMessage
        api.setBaseUrl(msg: msgArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setBaseUrlChannel.setMessageHandler(nil)
    }
    let disposeHubConnectionManagerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.fsignalr.HubConnectionManagerNativeApi.disposeHubConnectionManager\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeHubConnectionManagerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let msgArg = args[0] as! HubConnectionManagerIdMessage
        api.disposeHubConnectionManager(msg: msgArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeHubConnectionManagerChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol HubConnectionManagerFlutterApiProtocol {
  func onHubConnectionStateChanged(msg msgArg: OnHubConnectionStateChangedMessage, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onConnectionClosed(msg msgArg: OnHubConnectionClosedMessage, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onMessageReceived(msg msgArg: OnMessageReceivedMessage, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class HubConnectionManagerFlutterApi: HubConnectionManagerFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onHubConnectionStateChanged(msg msgArg: OnHubConnectionStateChangedMessage, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.fsignalr.HubConnectionManagerFlutterApi.onHubConnectionStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([msgArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onConnectionClosed(msg msgArg: OnHubConnectionClosedMessage, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.fsignalr.HubConnectionManagerFlutterApi.onConnectionClosed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([msgArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onMessageReceived(msg msgArg: OnMessageReceivedMessage, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.fsignalr.HubConnectionManagerFlutterApi.onMessageReceived\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([msgArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
